### ISSUE TITLE
Dropbox does not work on Ubuntu 19.04

### ISSUE THREAD

**Issue by GreatBahram** [dropbox/nautilus-dropbox#73]
Hi,
After I updated my system, it seems dropbox does not work property, it shows:
```python
Starting Dropbox...Traceback (most recent call last):
  File "/usr/bin/dropbox", line 1583, in <module>
    ret = main(sys.argv)
  File "/usr/bin/dropbox", line 1572, in main
    result = commands[argv[i]](argv[i+1:])
  File "/usr/bin/dropbox", line 1429, in start
    if not start_dropbox():
  File "/usr/bin/dropbox", line 757, in start_dropbox
    stderr=sys.stderr, stdout=f, close_fds=True, env=new_env)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format erro
```

**Comment by GreatBahram** [comment]
After I downloaded debian package from dropbox website, it logs below messsages:
````syslog
May 13 08:40:00 Doer update-notifier.desktop[4496]: Traceback (most recent call last):
May 13 08:40:00 Doer update-notifier.desktop[4496]:   File "/usr/bin/dropbox", line 1594, in <module>
May 13 08:40:00 Doer update-notifier.desktop[4496]:     ret = main(sys.argv)
May 13 08:40:00 Doer update-notifier.desktop[4496]:   File "/usr/bin/dropbox", line 1583, in main
May 13 08:40:00 Doer update-notifier.desktop[4496]:     result = commands[argv[i]](argv[i+1:])
May 13 08:40:00 Doer update-notifier.desktop[4496]:   File "/usr/bin/dropbox", line 1434, in start
May 13 08:40:00 Doer update-notifier.desktop[4496]:     if not start_dropbox():
May 13 08:40:00 Doer update-notifier.desktop[4496]:   File "/usr/bin/dropbox", line 755, in start_dropbox
May 13 08:40:00 Doer update-notifier.desktop[4496]:     stderr=sys.stderr, stdout=f, close_fds=True)
May 13 08:40:00 Doer update-notifier.desktop[4496]:   File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
May 13 08:40:00 Doer update-notifier.desktop[4496]:     restore_signals, start_new_session)
May 13 08:40:00 Doer update-notifier.desktop[4496]:   File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
May 13 08:40:00 Doer update-notifier.desktop[4496]:     raise child_exception_type(errno_num, err_msg, err_filename)
May 13 08:40:00 Doer update-notifier.desktop[4496]: OSError: [Errno 8] Exec format error: '/home/bahram/.dropbox-dist/dropboxd'

```

**Comment by GreatBahram** [comment]
Solved: I just removed `.dropbox-dist` directory, then started `dropbox` and it has been fixed.
